# There is no version 3.9 og the docker file format, 3.8 was the last one
# before the Docker Compose Specification took over. 3.9 is used to trigger
# an error if you're using way too old docker (newer ones will warn about
# version, but old ones should refuse)
version: "3.9"
services:
  presentation:
    build:
      context: presentation
    ports:
      - "8888:80"
    volumes:
      - ./presentation/index.html:/usr/share/nginx/html/index.html
      - ./presentation/files:/usr/share/nginx/html/files/
      - ./presentation/slides:/usr/share/nginx/html/slides/
